### ISSUE TITLE
CLI Template

### ISSUE THREAD

**Issue by wisesascha** [ptmt/react-native-desktop#12]
As far as I can tell the only thing left to get the cli to be able to generate a mac app is to create the proper templates. This wouldn't take very long but would require some standardization on how the applications are created. Some preliminary things are if it would be best to put some logic in an XIB or have everything wired up in code. Also the recommend distribution method for the library itself, would we want it to be distributed as a project that is downloaded and compiled with it, or a static library.

**Comment by ptmt** [comment]
Don't be getting templates mean that it's ready to public usage via npm? And that it would require support, documentation and at least most of APIs to be stabilized.

What kind of arguments you have for XIB since we still have to expose menu managment to js? Visual approach, the way is reccomended by Apple?
