### ISSUE TITLE
LayoutAnimation support

### ISSUE THREAD

**Issue by beretboat** [ptmt/react-native-desktop#24]
LayoutAnimation is really handy on react-native for iOS. It does not work here because some of the code is commented in RCTUIManager.m. I assume you commented the code because `NSView`  has no animation methods like `UIView` does? 

Anyway I found [a NSView category](https://github.com/connor/CMEqualizerIndicatorView/blob/master/CMEqualizerIndicatorView/NSView%2BNSViewAnimationWithBlocks.m) that simulate `UIView` animation methods using CoreAnimation APIs. But sadly it does not work at all. Any thoughts?

[Here's my change](https://github.com/beretboat/react-native-desktop/commit/cdc02aecb2ad0261658bbbecf303c4b0b80d80c5) to enable and test LayoutAnimation.

**Comment by ptmt** [comment]
You're right, LayoutAnimation is must have API. In fact, I played a while ago with it and managed to make LayoutAnimation work for certain `updateAnimation` cases, which animates `frame` by setting `animator` property:
```objective-c
[updateAnimation performAnimations:^{
          [[view animator] setFrame:frame];
          [view reactSetFrame:frame];
          for (RCTViewManagerUIBlock block in updateBlocks) {
            block(self, _viewRegistry);
          }
} withCompletionBlock:completion];
```
and `createAnimation` worked too but in different way, since it uses layer transforms.

You solution looks nice and we certanly should investigate more on it. Could you create a pull request?

Let's also add an UIExplorer example (or just extend LayoutEvents.js) for testing all kind of LayoutAnimation.
