### ISSUE TITLE
Wrong origin with NSPopover

### ISSUE THREAD

**Issue by BafS** [ptmt/react-native-desktop#76]
Hello,

First, tanks for this project, great job !

I try to wrap a react native application into a NSPopover but everything is shifted from the origin (about -8px, -8px). I am not sure it's a react native desktop bug but it seems to be.

![untitled 2](https://cloud.githubusercontent.com/assets/588205/14962604/f3fa7ee6-109f-11e6-8dfa-35c39adb10de.gif)

The NSPopover is basically created like 

```objectivec
  popover = [[NSPopover alloc] init];
  [popover setBehavior:NSPopoverBehaviorTransient];
  [popover setContentSize:NSMakeSize(200.0f, 515.0f)];
  popoverViewController = [[NSViewController alloc] initWithNibName:@"View" bundle:nil];
  popoverViewController.view = rootView;
  popover.contentViewController = popoverViewController;
```

Thank you

**Comment by ptmt** [comment]
@BafS thanks for reporting this. You're totally right! Since `NSPopover` overloads `NSObject`, not `NSWindow` to use private NSPopoverWindow implementation with some frame (13px in my case) around content view it messes with the [point locationInWindow]. I fixed that, please check. 

Happy to see you're trying RND!

**Comment by BafS** [comment]
Thank you for the quick fix, I just test and it works perfectly !
Happy that you develop RND :)
